//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

//Каждый следующий элемент ряда Фибоначчи получается при сложении двух предыдущих. Начиная с 1 и 2, первые 10 элементов будут:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//Найдите сумму всех четных элементов ряда Фибоначчи, которые не превышают четыре миллиона

const fibonacci = (a) => {
    if (a === 0) {
      return 0;
    }
  
    if (a === 1) {
      return 1;
    }
    return fibonacci(a - 2) + fibonacci(a - 1);
  };
  
  const sumOfodd = () => {
    const iter = (counter, acc) => {
      const numOfFibonacci = fibonacci(counter);
      if (acc > 4000000) {
        return acc;
      }
  
      if (numOfFibonacci % 2 === 0) {
        acc += numOfFibonacci;
      }
      return iter(counter + 1, acc);
    };
    return iter(0, 0)
  };
  sumOfodd();